# Generated by Django 6.0.1 on 2026-01-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_mentor_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrequest',
            name='mentorship_until',
            field=models.CharField(max_length=100),
        ),
    ]
