# Generated by Django 6.0 on 2026-01-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startups',
            old_name='bio',
            new_name='benefits',
        ),
    ]
