# Generated by Django 6.0 on 2026-01-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_comment_group_post_model_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='scope',
        ),
        migrations.AddField(
            model_name='post_model',
            name='tag',
            field=models.CharField(choices=[('idea_presentation', 'Idea Presentation'), ('accomplishment', 'Accomplishment'), ('announcement', 'Announcement')], default='idea_presentation', max_length=20),
        ),
    ]
